export const COURSE_LIST_REQUEST =" COURSE_LIST_REQUEST"
export const COURSE_LIST_SUCCESS ="COURSE_LIST_SUCCESS"
export const COURSE_LIST_FAIL ="COURSE_LIST_FAIL"
export const COURSE_DELETE_SUCCESS ="COURSE_DELETE_SUCCESS"
export const COURSE_DELETE_REQUEST ="COURSE_DELETE_REQUEST"
export const COURSE_DELETE_FAIL ="COURSE_DELETE_FAIL"



export const COURSE_POST_REQUEST =" COURSE_POST_REQUEST"
export const COURSE_POST_SUCCESS ="COURSE_POST_SUCCESS"
export const COURSE_POST_FAIL ="COURSE_POST_FAIL"

export const COURSE_EDIT_REQUEST =" COURSE_EDIT_REQUEST"
export const COURSE_EDIT_SUCCESS ="COURSE_EDIT_SUCCESS"
export const COURSE_EDIT_FAIL ="COURSE_EDIT_FAIL"